add expand_all_parents directive to treeControl
nickperkinslondon/angular-bootstrap-nav-tree pull request #85
Opened 2015-06-04 16:05 UTC by HerrShabi

2015-06-04 16:48 UTC, benoror commented
+1

2015-06-04 18:52 UTC, meilke commented
:+1:

2015-06-05 07:00 UTC, raoulus commented
:+1:

2017-03-03 19:33 UTC, nickperkinslondon requested changes
change should be made to the source coffeescript file ( i know this is old....just sayin...)

2017-03-03 22:02 UTC, closed without merging